name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.2.1
      with:
        version: 5.12.6
        
    - name: cmake
      run: cmake .
      
    - name: make
      run: make
