name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        qt_version: [5.11, 5.12, 5.13, 5.14]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.2.1
      with:
        version: ${{ matrix.qt_version }}

    - name: cmake
      run: cmake .

    - name: make
      run: make

    - name: Build example - basic (cmake)
      run: cmake . && make
      working-directory: examples/basic/

    - name: Build example - calculator (cmake)
      run: cmake . && make
      working-directory: examples/calculator/

    - name: Build example - sending_arguments (cmake)
      run: cmake . && make
      working-directory: examples/sending_arguments/
